import {list} from "@vercel/blob";
export const dynamic="force-dynamic";
async function photos(){if(!process.env.BLOB_READ_WRITE_TOKEN)return [];try{return (await list({prefix:"gallery/"})).blobs.map(b=>({url:b.url,pathname:b.pathname}));}catch{return [];}}
export default async function Home(){const p=await photos();return <main>
<header className="topbar"><div className="container nav"><a className="brand" href="#start">CHATA <span>POLSKA</span></a><nav><a href="#gazetka">Gazetka</a><a href="#sklep">Sklep</a><a href="#zdjecia">Zdjęcia</a><a href="#kontakt">Kontakt</a></nav></div></header>
<section id="start" className="hero"><div className="container heroGrid"><div><p className="eyebrow">CHATA POLSKA • RAWICZ</p><h1>Codzienne zakupy.<br/><span>Blisko Ciebie.</span></h1><p className="lead">Sprawdź promocje, informacje o sklepie i zaplanuj dojazd do Chaty Polskiej w Rawiczu.</p><div className="actions"><a className="button" href="#gazetka">Zobacz gazetkę</a><a className="textButton" href="#sklep">Jak dojechać ↓</a></div></div><div className="heroCard"><small>CHATA POLSKA</small><strong>Promocje<br/>i zakupy.</strong><span>Rawicz • Spokojna</span></div></div></section>
<section id="gazetka" className="section"><div className="container"><div className="sectionHead"><div><p className="eyebrow">GAZETKA PROMOCYJNA</p><h2>Najnowsze promocje</h2></div><a className="textButton" href="https://www.chatapolska.pl/" target="_blank">Oficjalna strona ↗</a></div><div className="flyer"><h3>Aktualna gazetka</h3><p>Aktualne promocje sprawdzisz na oficjalnej stronie Chaty Polskiej.</p><a className="button" href="https://www.chatapolska.pl/" target="_blank">Otwórz gazetkę ↗</a></div></div></section>
<section className="section light"><div className="container featureGrid"><div><p className="eyebrow">W SKLEPIE</p><h2>Wszystko pod ręką.</h2><p className="lead">Informacje dotyczące sklepu Chata Polska w Rawiczu.</p></div><div className="infoList"><div><b>01</b><span>Aktualna gazetka</span></div><div><b>02</b><span>Adres i nawigacja</span></div><div><b>03</b><span>Zdjęcia sklepu</span></div></div></div></section>
<section id="sklep" className="section"><div className="container storeGrid"><div><p className="eyebrow">CHATA POLSKA RAWICZ</p><h2>Znajdź nas<br/>w Rawiczu.</h2><div className="addressCard"><span className="boxLabel">ADRES</span><strong>Spokojna</strong><span>63-900 Rawicz</span></div><div className="actions"><a className="button" href="https://www.google.com/maps/search/?api=1&query=Chata%20Polska%20Spokojna%2C%2063-900%20Rawicz" target="_blank">Nawiguj do sklepu ↗</a><a className="textButton" href="https://www.chatapolska.pl/" target="_blank">Chata Polska ↗</a></div></div><div id="kontakt" className="contactBox"><p className="boxLabel">INFORMACJE</p><h3>Chata Polska</h3><p><strong>Adres</strong><br/>Spokojna, 63-900 Rawicz</p><p><strong>Godziny</strong><br/>Przed wizytą sprawdź aktualne godziny w Google.</p><p><strong>Telefon sklepu</strong><br/>Brak potwierdzonego numeru telefonu sklepu.</p></div></div></section>
<section id="zdjecia" className="section light"><div className="container"><div className="sectionHead"><div><p className="eyebrow">GALERIA</p><h2>Sklep i okolica</h2></div><a className="textButton" href="/admin">Panel właściciela</a></div>{p.length?<div className="gallery">{p.map(x=><img key={x.pathname} src={x.url} alt="Chata Polska Rawicz" loading="lazy"/>)}</div>:<div className="emptyGallery">Galeria jest gotowa. Zdjęcia dodasz z prywatnego panelu właściciela.</div>}</div></section>
<footer><div className="container footerInner"><b>CHATA POLSKA</b><span>Rawicz • Spokojna</span><a href="https://www.chatapolska.pl/" target="_blank">Oficjalna strona ↗</a></div></footer>
</main>}